apiVersion: v1
kind: Pod
metadata:
  name: nginx-toleration
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "tech"
    operator: "Equal"
    value: "titans"
    effect: "NoSchedule"
